# Generated by Django 5.1.1 on 2024-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
