# Generated by Django 5.1.1 on 2024-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='feedback',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='source_language',
            field=models.CharField(default='Spanish', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='target_language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
