# Generated by Django 5.1.1 on 2024-10-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_question_feedback_question_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
