# Generated by Django 5.1.1 on 2024-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_quiz_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='currentStreakCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='hasCompletedQuiz',
            field=models.BooleanField(default=False),
        ),
    ]
