# Generated by Django 5.1.1 on 2024-10-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_quiz_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
