# Generated by Django 5.1.1 on 2024-10-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_member_currentstreakcount_member_hascompletedquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='currentStreakCount',
            new_name='streakCount',
        ),
    ]
