# Generated by Django 5.1.1 on 2024-10-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_quiz_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
    ]
