# Generated by Django 5.1.1 on 2024-10-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_streakresetlog'),
        ('home', '0015_remove_quiz_user'),
    ]

    operations = [
    ]
