# Generated by Django 5.1.1 on 2024-10-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merge_0013_streakresetlog_0015_remove_quiz_user'),  # noqa: E501
    ]

    operations = [
        migrations.DeleteModel(
            name='StreakResetLog',
        ),
        migrations.RemoveField(
            model_name='member',
            name='hasCompletedQuiz',
        ),
        migrations.RemoveField(
            model_name='member',
            name='streakCount',
        ),
    ]
