# Generated by Django 5.1.1 on 2024-10-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_streakresetlog_remove_member_hascompletedquiz_and_more'),  # noqa: E501
    ]

    operations = [
        migrations.CreateModel(
            name='LastStreakReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('lastReset', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='hasCompletedQuiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='streakCount',
            field=models.IntegerField(default=0),
        ),
    ]
