# Generated by Django 5.1.1 on 2024-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_quiz_is_completed_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='longestStreak',
            field=models.IntegerField(default=0),
        ),
    ]
