# Generated by Django 5.1.1 on 2024-11-11 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_member_longeststreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dateJoined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),  # noqa: E501
            preserve_default=False,
        ),
    ]
