# Generated by Django 5.1.1 on 2024-11-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_quiz_is_active_quiz_user'),
        ('home', '0021_member_datejoined'),
    ]

    operations = [
    ]
