# Generated by Django 5.1.1 on 2024-11-26 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20241113_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_next',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='curr_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.question'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='quiz',
            name='incorrect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_questions', to='home.question'),  # noqa: E501
        ),
    ]
