# Generated by Django 5.1.1 on 2024-12-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_wordoftheday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordOfTheDay',
            new_name='WordOfTheDayChecker',
        ),
    ]
