# Generated by Django 5.1.1 on 2024-12-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_wordoftheday_wordofthedaychecker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordOfTheDayChecker',
            new_name='WordOfTheDayTracker',
        ),
    ]
